window.SONGS = [
  { title: "That's The Way To Do It", game: "Astro's Playroom", file: "music/01. That's The Way To Do It.mp3" },
  { title: "CPU Plaza", game: "Astro's Playroom", file: "music/02. CPU Plaza.mp3" },
  { title: "I'm Your GPU", game: "Astro's Playroom", file: "music/03. I'm Your GPU.mp3" },
  { title: "SSD", game: "Astro's Playroom", file: "music/04. SSD.mp3" },
  { title: "Follow Me (Into The Storm)", game: "Astro's Playroom", file: "music/05. Follow Me (Into The Storm) [Playroom Remix].mp3" },
  { title: "Botdi Beach", game: "Astro's Playroom", file: "music/06. Botdi Beach.mp3" },
  { title: "Cooling Springs", game: "Astro's Playroom", file: "music/07. Cooling Springs.mp3" },
  { title: "PlayStation Labo & Gatcha", game: "Astro's Playroom", file: "music/08. PlayStation Labo & Gatcha.mp3" },
  { title: "GPU Jungle", game: "Astro's Playroom", file: "music/09. GPU Jungle (Powerup & Boss).mp3" },
  { title: "SSD Speedway", game: "Astro's Playroom", file: "music/10. SSD Speedway (Powerup & Boss).mp3" },
  { title: "CPU Plaza (After Dark)", game: "Astro's Playroom", file: "music/11. CPU Plaza (After Dark).mp3" },
  { title: "They Don't Make'm Like They Used To", game: "Astro's Playroom", file: "music/12. They Don't Make'm Like They Used To.mp3" },
  { title: "CRT-Rex", game: "Astro's Playroom", file: "music/13. CRT-Rex.mp3" },
  { title: "4K-Rex", game: "Astro's Playroom", file: "music/14. 4K-Rex.mp3" },
  { title: "Let's Do This", game: "Astro's Playroom", file: "music/15. Let's Do This.mp3" },
  { title: "Goal", game: "Astro's Playroom", file: "music/16. Goal.mp3" },
  { title: "Uplifting Little Number", game: "Astro's Playroom", file: "music/17. Uplifting Little Number.mp3" },
  { title: "I Am Astro Bot (Playroom Remix)", game: "Astro's Playroom", file: "music/18. I Am Astro Bot [Playroom Remix].mp3" },
  { title: "Memories of Play", game: "Astro's Playroom", file: "music/19. Memories of Play.mp3" },
  { title: "CPU Plaza (Mashup Overture)", game: "Astro's Playroom", file: "music/20. CPU Plaza (Mashup Overture).mp3" },
  { title: "Happy Ever After", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Happy Ever After - By Kenneth M C Young.mp3" },
  { title: "I am ASTRO BOT", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - I am ASTRO BOT - By Kenneth M C Young.mp3" },
  { title: "Let's Do This", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Lets Do This - By Kenneth M C Young.mp3" },
  { title: "Come On Then", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Come On Then (Alien Boss) - By Kenneth M C Young.mp3" },
  { title: "All Tied Up", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - All Tied Up (Spider Boss) - By Kenneth M C Young.mp3" },
  { title: "12 Bar BOT", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - 12 Bar BOT (Funfair Remix) - By Kenneth M C Young.mp3" },
  { title: "Inside The Whale", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Inside The Whale (Fishy Cave) - By Kenneth M C Young.mp3" },
  { title: "Ninja Bots", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Ninja Bots (Remix) - By Kenneth M C Young.mp3" },
  { title: "Decidedly Spooky", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Decidedly Spooky - By Kenneth M C Young.mp3" },
  { title: "Cool Fin", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Cool Fin (Shark Boss) - By Kenneth M C Young.mp3" },
  { title: "Polyethylene Paradise", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Polyethylene Paradise - By Kenneth M C Young.mp3" },
  { title: "Seeking Shade", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Seeking Shade - By Kenneth M C Young.mp3" },
  { title: "Sucka", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Sucka (Octopus Boss) - By Kenneth M C Young.mp3" },
  { title: "A Fire In Your Mind", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - A Fire In Your Mind - By Kenneth M C Young.mp3" },
  { title: "Off The Rails", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Off The Rails - By Kenneth M C Young.mp3" },
  { title: "What Was That", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - What Was That (Scary Cave) - By Kenneth M C Young.mp3" },
  { title: "Hatch A Plan", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Hatch A Plan (Bird Boss) - By Kenneth M C Young.mp3" },
  { title: "Follow Me", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Follow Me (Into The Storm) - By Kenneth M C Young.mp3" },
  { title: "Discotree", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Discotree - By Kenneth M C Young.mp3" },
  { title: "Tan Traditional", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Tan Traditional - By Kenneth M C Young.mp3" },
  { title: "Bite It", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Bite It (Gorilla Boss) - By Kenneth M C Young.mp3" },
  { title: "Tite Mites", game: "Astro Bot", file: "music/Tite Mites.mp3" },
  { title: "12 bar BOT", game: "Astro Bot", file: "music/12 bar BOT.mp3" },
  { title: "ASTROnomical", game: "Astro Bot", file: "music/ASTROnomical.mp3" }
];