window.SONGS = [
  { title: "That's The Way To Do It", game: "Astro's Playroom", file: "music/01. That's The Way To Do It.mp3" },
  { title: "CPU Plaza", game: "Astro's Playroom", file: "music/02. CPU Plaza.mp3" },
  { title: "I'm Your GPU", game: "Astro's Playroom", file: "music/03. I'm Your GPU.mp3" },
  { title: "SSD", game: "Astro's Playroom", file: "music/04. SSD.mp3" },
  { title: "Follow Me (Into The Storm)", game: "Astro's Playroom", file: "music/05. Follow Me (Into The Storm) [Playroom Remix].mp3" },
  { title: "Botdi Beach", game: "Astro's Playroom", file: "music/06. Botdi Beach.mp3" },
  { title: "Cooling Springs", game: "Astro's Playroom", file: "music/07. Cooling Springs.mp3" },
  { title: "PlayStation Labo & Gatcha", game: "Astro's Playroom", file: "music/08. PlayStation Labo & Gatcha.mp3" },
  { title: "GPU Jungle", game: "Astro's Playroom", file: "music/09. GPU Jungle (Powerup & Boss).mp3" },
  { title: "SSD Speedway", game: "Astro's Playroom", file: "music/10. SSD Speedway (Powerup & Boss).mp3" },
  { title: "CPU Plaza (After Dark)", game: "Astro's Playroom", file: "music/11. CPU Plaza (After Dark).mp3" },
  { title: "They Don't Make'm Like They Used To", game: "Astro's Playroom", file: "music/12. They Don't Make'm Like They Used To.mp3" },
  { title: "CRT-Rex", game: "Astro's Playroom", file: "music/13. CRT-Rex.mp3" },
  { title: "4K-Rex", game: "Astro's Playroom", file: "music/14. 4K-Rex.mp3" },
  { title: "Let's Do This", game: "Astro's Playroom", file: "music/15. Let's Do This.mp3" },
  { title: "Goal", game: "Astro's Playroom", file: "music/16. Goal.mp3" },
  { title: "Uplifting Little Number", game: "Astro's Playroom", file: "music/17. Uplifting Little Number.mp3" },
  { title: "I Am Astro Bot (Playroom Remix)", game: "Astro's Playroom", file: "music/18. I Am Astro Bot [Playroom Remix].mp3" },
  { title: "Memories of Play", game: "Astro's Playroom", file: "music/19. Memories of Play.mp3" },
  { title: "CPU Plaza (Mashup Overture)", game: "Astro's Playroom", file: "music/20. CPU Plaza (Mashup Overture).mp3" },
  { title: "Happy Ever After", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Happy Ever After - By Kenneth M C Young.mp3" },
  { title: "I am ASTRO BOT", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - I am ASTRO BOT - By Kenneth M C Young.mp3" },
  { title: "Let's Do This", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Lets Do This - By Kenneth M C Young.mp3" },
  { title: "Come On Then", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Come On Then (Alien Boss) - By Kenneth M C Young.mp3" },
  { title: "All Tied Up", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - All Tied Up (Spider Boss) - By Kenneth M C Young.mp3" },
  { title: "12 Bar BOT", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - 12 Bar BOT (Funfair Remix) - By Kenneth M C Young.mp3" },
  { title: "Inside The Whale", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Inside The Whale (Fishy Cave) - By Kenneth M C Young.mp3" },
  { title: "Ninja Bots", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Ninja Bots (Remix) - By Kenneth M C Young.mp3" },
  { title: "Decidedly Spooky", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Decidedly Spooky - By Kenneth M C Young.mp3" },
  { title: "Cool Fin", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Cool Fin (Shark Boss) - By Kenneth M C Young.mp3" },
  { title: "Polyethylene Paradise", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Polyethylene Paradise - By Kenneth M C Young.mp3" },
  { title: "Seeking Shade", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Seeking Shade - By Kenneth M C Young.mp3" },
  { title: "Sucka", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Sucka (Octopus Boss) - By Kenneth M C Young.mp3" },
  { title: "A Fire In Your Mind", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - A Fire In Your Mind - By Kenneth M C Young.mp3" },
  { title: "Off The Rails", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Off The Rails - By Kenneth M C Young.mp3" },
  { title: "What Was That", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - What Was That (Scary Cave) - By Kenneth M C Young.mp3" },
  { title: "Hatch A Plan", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Hatch A Plan (Bird Boss) - By Kenneth M C Young.mp3" },
  { title: "Follow Me", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Follow Me (Into The Storm) - By Kenneth M C Young.mp3" },
  { title: "Discotree", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Discotree - By Kenneth M C Young.mp3" },
  { title: "Tan Traditional", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Tan Traditional - By Kenneth M C Young.mp3" },
  { title: "Bite It", game: "Astro Bot Rescue Mission", file: "music/Astro Bot Rescue Mission - Soundtrack - Bite It (Gorilla Boss) - By Kenneth M C Young.mp3" },
  { title: "Tite Mites", game: "Astro Bot", file: "music/Tite Mites.mp3" },
  { title: "12 bar BOT", game: "Astro Bot", file: "music/12 bar BOT.mp3" },
  { title: "ASTROnomical", game: "Astro Bot", file: "music/ASTROnomical.mp3" }

{ title: "Quel Fromage", game: "Astro Bot", file: "music/21. Quel Fromage - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Sucka (Octopus Boss)", game: "Astro Bot", file: "music/22. Sucka (Octopus Boss) - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Tread Lightly", game: "Astro Bot", file: "music/23. Tread Lightly - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Bot of War", game: "Astro Bot", file: "music/24. Bot of War - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Villisvin", game: "Astro Bot", file: "music/25. Villisvin - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Twinkle Toes", game: "Astro Bot", file: "music/26. Twinkle Toes - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Retro Rampage (Speedy Remix)", game: "Astro Bot", file: "music/27. Retro Rampage (Speedy Remix) - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Casino (No Guarantino)", game: "Astro Bot", file: "music/28. Casino (No Guarantino) - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Trapped In Time", game: "Astro Bot", file: "music/29. Trapped In Time - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Rattled (Snakey Cave)", game: "Astro Bot", file: "music/30. Rattled (Snakey Cave) - Astro Bot OST (Official Video Game Soundtrack).mp3" },

{ title: "Ninja Bots Konnichiwa", game: "Astro Bot", file: "music/33. Ninja Bots Konnichiwa - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Hissy Fit (Snake Boss)", game: "Astro Bot", file: "music/35. Hissy Fit (Snake Boss) - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Drake's BOTune", game: "Astro Bot", file: "music/36. Drake's BOTune - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "What Was That?", game: "Astro Bot", file: "music/37. What Was That_  - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "I Haven't Thought That Far Ahead", game: "Astro Bot", file: "music/38. I Haven't Thought That Far Ahead - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Broken Bridge", game: "Astro Bot", file: "music/40. Broken Bridge - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Pit of Peril", game: "Astro Bot", file: "music/41. Pit of Peril - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Muteki Funk", game: "Astro Bot", file: "music/42. Muteki Funk - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Marine Serene", game: "Astro Bot", file: "music/43. Marine Serene - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Frightfully Fun", game: "Astro Bot", file: "music/46. Frightfully Fun - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Invisible Punk (Chameleon Boss)", game: "Astro Bot", file: "music/47. Invisible Punk (Chameleon Boss) - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Ninja Bots Sayonara", game: "Astro Bot", file: "music/49. Ninja Bots Sayonara - Astro Bot OST (Official Video Game Soundtrack).mp3" },

{ title: "Trapped In Time (Acoustic Mix)", game: "Astro Bot", file: "music/52. Trapped In Time (Acoustic Mix) - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Freeze Your BOT Off", game: "Astro Bot", file: "music/54. Freeze Your BOT Off - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Luna", game: "Astro Bot", file: "music/56. Luna - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Sola", game: "Astro Bot", file: "music/57. Sola - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Firebooter", game: "Astro Bot", file: "music/59. Firebooter - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Every Dawn & Dusk", game: "Astro Bot", file: "music/61. Every Dawn & Dusk - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "The Strength To Stand Alone", game: "Astro Bot", file: "music/62. The Strength To Stand Alone - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Restore Power", game: "Astro Bot", file: "music/63. Restore Power - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Takedown", game: "Astro Bot", file: "music/64. Takedown - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "The Launch", game: "Astro Bot", file: "music/68. The Launch - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Surprise!", game: "Astro Bot", file: "music/70. Surprise! - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Build a Bot", game: "Astro Bot", file: "music/71. Build a Bot - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Better Together", game: "Astro Bot", file: "music/72. Better Together - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Fixin'", game: "Astro Bot", file: "music/74. Fixin' - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Gatcha", game: "Astro Bot", file: "music/76. Gatcha - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Safari Park", game: "Astro Bot", file: "music/77 . Safari Park - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Changing Room", game: "Astro Bot", file: "music/78. Changing Room - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Dual Speeder Garage", game: "Astro Bot", file: "music/79.  Dual Speeder Garage - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Secret", game: "Astro Bot", file: "music/80. Secret - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Perseverance", game: "Astro Bot", file: "music/83. Perseverance - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Retro Rampage", game: "Astro Bot", file: "music/84. Retro Rampage - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Memories of Home", game: "Astro Bot", file: "music/86. Memories of Home - Astro Bot OST (Official Video Game Soundtrack).mp3" },
{ title: "Announce Trailer", game: "Astro Bot", file: "music/87. Announce Trailer - Astro Bot OST (Official Video Game Soundtrack).mp3" }
];